config/routes.rb
GestionDit::Application.routes.draw do
  
  match "/planificaciones_semanales/new/:usuario_id/:semana_id", :to => 'planificaciones_semanales#new'
  
  resources :planificaciones_semanales

  resources :semanas

  resources :requerimientos_areas

  resources :areas_usuarios

  resources :estados

  match "/planificaciones_requerimientos/new/:id" => "planificaciones_requerimientos#new"

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :planificaciones_requerimientos

  resources :planificaciones

  resources :gerencia

  resources :requerimientos

  resources :areas

  resources :usuarios

  resources :aplicaciones

  resources :tipos_requerimientos

  root :to => 'planificaciones#index' 

end

app/controllers/requerimientos_areas_controller.rb
class RequerimientosAreasController < ApplicationController
  # GET /requerimientos_areas
  # GET /requerimientos_areas.json
  def index
    @requerimientos_areas = RequerimientoArea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requerimientos_areas }
    end
  end

  # GET /requerimientos_areas/1
  # GET /requerimientos_areas/1.json
  def show
    @requerimiento_area = RequerimientoArea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @requerimiento_area }
    end
  end

  # GET /requerimientos_areas/new
  # GET /requerimientos_areas/new.json
  def new
    @requerimiento_area = RequerimientoArea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @requerimiento_area }
    end
  end

  # GET /requerimientos_areas/1/edit
  def edit
    @requerimiento_area = RequerimientoArea.find(params[:id])
  end

  # POST /requerimientos_areas
  # POST /requerimientos_areas.json
  def create
    @requerimiento_area = RequerimientoArea.new(params[:requerimiento_area])
    @requerimiento_area.estimacion = 0

    respond_to do |format|
      if @requerimiento_area.save
        format.html { redirect_to @requerimiento_area, notice: 'Requerimiento area was successfully created.' }
        format.json { render json: @requerimiento_area, status: :created, location: @requerimiento_area }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @requerimiento_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requerimientos_areas/1
  # PUT /requerimientos_areas/1.json
  def update
    @requerimiento_area = RequerimientoArea.find(params[:id])

    respond_to do |format|
      if @requerimiento_area.update_attributes(params[:requerimiento_area])
        format.html { redirect_to @requerimiento_area, notice: 'Requerimiento area was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @requerimiento_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requerimientos_areas/1
  # DELETE /requerimientos_areas/1.json
  def destroy
    @requerimiento_area = RequerimientoArea.find(params[:id])
    @requerimiento_area.destroy

    respond_to do |format|
      format.html { redirect_to requerimientos_areas_url }
      format.json { head :ok }
      format.js
    end
  end
end

app/helpers/requerimientos_areas_helper.rb
module RequerimientosAreasHelper
end

app/views/requerimientos_areas/_form.html.erb
<%= form_for(@requerimiento_area) do |f| %>
  <% if @requerimiento_area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requerimiento_area.errors.count, "error") %> prohibited this requerimiento_area from being saved:</h2>

      <ul>
      <% @requerimiento_area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :requerimiento %><br />
    <%= f.text_field :requerimiento %>
  </div>
  <div class="field">
    <%= f.label :estimacion %><br />
    <%= f.text_field :estimacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requerimientos_areas/_requerimiento_area.html.erb
	<tr id="ra_<%= requerimiento_area.id %>">
		<td><%= best_in_place requerimiento_area, :etapa, nil: 'Clic aquí para editar' %></td>
		<td><%= requerimiento_area.area.nombre %></td>
		<td><%= best_in_place requerimiento_area, :estimacion, :html_attrs => { :class => 'input-mini' } %></td>
		<td><%= link_to 'Quitar', requerimiento_area, confirm: '¿Está seguro?', method: :delete, :remote => true %></td>
	</tr>

app/views/requerimientos_areas/create.js.erb
	$('#requerimientos_areas').prepend('<%= escape_javascript(render(@requerimiento_area)) %>');
	$('#ra_<%= @requerimiento_area.id %>').hide();	
	$('#ra_<%= @requerimiento_area.id %>').show("slow");
	
	// Hacer funcionar el best_in_place en la tablita apenas se agregan.
	$('.best_in_place').best_in_place();

app/views/requerimientos_areas/destroy.js.erb
	$('#ra_<%= @requerimiento_area.id %>').toggleClass('sobreplanificado');
	$('#ra_<%= @requerimiento_area.id %>').hide("slow");

app/views/requerimientos_areas/edit.html.erb
<h1>Editing requerimiento_area</h1>

<%= render 'form' %>

<%= link_to 'Show', @requerimiento_area %> |
<%= link_to 'Back', requerimientos_areas_path %>

app/views/requerimientos_areas/index.html.erb
	<table class="table table-bordered table-striped">
		<thead>
	  		<tr>
	  			<th>Etapa</th>
			    <th>&Aacute;rea</th>
			    <th>Estimaci&oacute;n</th>
			    <th>&nbsp;</th>
			</tr>
		</thead>
		<tbody id="requerimientos_areas">
			<%= render requerimientos_areas %>
		</tbody>
	</table>

app/views/requerimientos_areas/new.html.erb
<h1>New requerimiento_area</h1>

<%= render 'form' %>

<%= link_to 'Back', requerimientos_areas_path %>

app/views/requerimientos_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Area:</b>
  <%= @requerimiento_area.area %>
</p>

<p>
  <b>Requerimiento:</b>
  <%= @requerimiento_area.requerimiento %>
</p>

<p>
  <b>Estimacion:</b>
  <%= @requerimiento_area.estimacion %>
</p>


<%= link_to 'Edit', edit_requerimiento_area_path(@requerimiento_area) %> |
<%= link_to 'Back', requerimientos_areas_path %>