config/routes.rb
GestionDit::Application.routes.draw do
  
  match "/planificaciones_semanales/new/:usuario_id/:semana_id", :to => 'planificaciones_semanales#new'
  
  resources :planificaciones_semanales

  resources :semanas

  resources :requerimientos_areas

  resources :areas_usuarios

  resources :estados

  match "/planificaciones_requerimientos/new/:id" => "planificaciones_requerimientos#new"

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :planificaciones_requerimientos

  resources :planificaciones

  resources :gerencia

  resources :requerimientos

  resources :areas

  resources :usuarios

  resources :aplicaciones

  resources :tipos_requerimientos

  root :to => 'planificaciones#index' 

end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id         :integer         primary key
#  nombre     :string(255)
#  created_at :timestamp
#  updated_at :timestamp
#

class Area < ActiveRecord::Base
  has_many :areas_usuarios, :class_name => "AreaUsuario"
  
  def texto_miembros
    texto = ""
    
    unless self.areas_usuarios.blank?
      self.areas_usuarios.each do |au|
        texto += ", " unless texto.empty?
        texto += au.usuario.login
      end
    end
    
    texto
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.order(:nombre)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  def remove_usuario
    area = Area.find(params[:id])
    usuario = Usuario.find(params[:usuario_id])

    redirect_to area_path(area)    
  end

  def add_usuario
    area = Area.find(params[:id])
    usuario = Usuario.find(params[:usuario_id])
    
    area_usuario = AreaUsuario.new
    area_usuario.area = area
    area_usuario.usuario = usuario
    area_usuario.save!
    
    redirect_to area_path(area)
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
	<%= form_for(@area, :html => {:class => 'form-horizontal'}) do |f| %>
  		<% if @area.errors.any? %>
    		<div id="error_explanation">
      			<h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>
      			<ul>
      				<% @area.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      				<% end %>
      			</ul>
    		</div>
  		<% end %>

 		<div class="control-group">
    		<%= f.label :nombre, :class => 'control-label' %>
    		<div class="controls"><%= f.text_field :nombre %></div>
  		</div>
  		<div class="form-actions">
    		<%= f.submit 'Grabar', :class => 'btn btn-primary' %>
    		<%= link_to 'Volver', areas_path, :class => 'btn' %>
  		</div>
	<% end %>

app/views/areas/edit.html.erb
	<div class="page-header">
		<h1>Editando area</h1>
	</div>

	<%= render 'form' %>

app/views/areas/index.html.erb
	<div class="page-header">
		<h1>Listando &aacute;reas</h1>
	</div>

	<table class="table table-bordered table-striped">
		<thead>
		  <tr>
		    <th>Nombre</th>
		    <th>Miembros</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		</thead>
		<tbody>
			<% @areas.each do |area| %>
			  <tr>
			    <td><%= area.nombre %></td>
			    <td><%= area.texto_miembros %></td>
			    <td><%= link_to 'Ver', area %></td>
			    <td><%= link_to 'Editar', edit_area_path(area) %></td>
			    <td><%= link_to 'Destruir', area, confirm: '¿Está seguro?', method: :delete %></td>
			  </tr>
			<% end %>
		</tbody>
	</table>

	<div class="form-actions">
		<%= link_to 'Nueva área', new_area_path, :class => 'btn btn-primary' %>
	</div>

app/views/areas/new.html.erb
	<div class="page-header">
		<h1>Nueva &aacute;rea</h1>
	</div>

	<%= render 'form' %>

app/views/areas/show.html.erb
	<legend>Información del área</legend>
	
	<div class="row">
		<div class="span12">
			<p id="notice"><%= notice %></p>
		</div>
	</div>

	<div class="row">
		<div class="span6">
			<p>
			  <b>Nombre:</b>
			  <%= @area.nombre %>
			</p>
		</div>
	</div>

	<br />

	<legend>Usuarios del área</legend>

	<div class="row">
		<div class="span6">
			<%= form_tag("/areas_usuarios", :method => 'post', :class => 'form-horizontal', :remote => true) do %>
				<input type="hidden" name="area_usuario[area_id]" value="<%= @area.id %>"/>
				<select name="area_usuario[usuario_id]">
					<% @usuarios.each do |u| %>
						<option value="<%= u.id %>"><%= u.apellido %>, <%= u.nombre %></option>
					<% end %>
				</select>
				<input type="submit" value="Agregar al área" class="btn btn-primary" />
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="span6">
			<%= render  :template => 'areas_usuarios/index', :locals => {:areas_usuarios => @area.areas_usuarios} %>			
		</div>
	</div>

	<div class="form-actions">
		<%= link_to 'Editar', edit_area_path(@area), :class => 'btn' %>
		<%= link_to 'Volver', areas_path, :class => 'btn' %>
	</div>