config/routes.rb
GestionDit::Application.routes.draw do
  
  match "/planificaciones_semanales/new/:usuario_id/:semana_id", :to => 'planificaciones_semanales#new'
  
  resources :planificaciones_semanales

  resources :semanas

  resources :requerimientos_areas

  resources :areas_usuarios

  resources :estados

  match "/planificaciones_requerimientos/new/:id" => "planificaciones_requerimientos#new"

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :planificaciones_requerimientos

  resources :planificaciones

  resources :gerencia

  resources :requerimientos

  resources :areas

  resources :usuarios

  resources :aplicaciones

  resources :tipos_requerimientos

  root :to => 'planificaciones#index' 

end

app/models/estado.rb
# == Schema Information
#
# Table name: estados
#
#  id         :integer         primary key
#  nombre     :string(255)
#  created_at :timestamp
#  updated_at :timestamp
#

class Estado < ActiveRecord::Base
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.json
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render json: @estado, status: :created, location: @estado }
      else
        format.html { render action: "new" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.json
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to estados_url }
      format.json { head :ok }
    end
  end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
	<%= form_for(@estado, :html => {:class => 'form-horizontal'}) do |f| %>
  		<% if @estado.errors.any? %>
    		<div id="error_explanation">
      			<h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>
      			<ul>
      				<% @estado.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      				<% end %>
      			</ul>
    		</div>
  		<% end %>

  		<div class="control-group">
    		<%= f.label :nombre, :class => 'control-label' %>
    		<div class="controls"><%= f.text_field :nombre %></div>
  		</div>
  		
  		<div class="form-actions">
    		<%= f.submit 'Grabar', :class => 'btn btn-primary' %>
    		<%= link_to 'Volver', estados_path, :class => 'btn' %>
  		</div>
	<% end %>

app/views/estados/edit.html.erb
	<div class="page-header">
		<h1>Editando estado</h1>
	</div>

	<%= render 'form' %>

app/views/estados/index.html.erb
	<div class="page-header">
		<h1>Listando estados</h1>
	</div>

	<table class="table table-bordered table-striped">
		<thead>
		  <tr>
		    <th>Nombre</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		</thead>
		<tbody>
			<% @estados.each do |estado| %>
			  <tr>
			    <td><%= estado.nombre %></td>
			    <td><%= link_to 'Ver', estado %></td>
			    <td><%= link_to 'Editar', edit_estado_path(estado) %></td>
			    <td><%= link_to 'Destruir', estado, confirm: '¿Está seguro?', method: :delete %></td>
			  </tr>
			<% end %>
		</tbody>
	</table>

	<div class="form-actions">
		<%= link_to 'Nuevo estado', new_estado_path, :class => 'btn btn-primary' %>
	</div>

app/views/estados/new.html.erb
	<div class="page-header">
		<h1>Nuevo estado</h1>
	</div>

	<%= render 'form' %>

app/views/estados/show.html.erb
	<div class="row">
		<div class="span12">
			<p id="notice"><%= notice %></p>
		</div>
	</div>

	<div class="row">
		<div class="span6">
			<p>
			  <b>Nombre:</b>
			  <%= @estado.nombre %>
			</p>
		</div>
	</div>

	<div class="form-actions">
		<%= link_to 'Editar', edit_estado_path(@estado), :class => 'btn' %>
		<%= link_to 'Volver', estados_path, :class => 'btn' %>
	</div>