config/routes.rb
GestionDit::Application.routes.draw do
  
  match "/planificaciones_semanales/new/:usuario_id/:semana_id", :to => 'planificaciones_semanales#new'
  
  resources :planificaciones_semanales

  resources :semanas

  resources :requerimientos_areas

  resources :areas_usuarios

  resources :estados

  match "/planificaciones_requerimientos/new/:id" => "planificaciones_requerimientos#new"

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :planificaciones_requerimientos

  resources :planificaciones

  resources :gerencia

  resources :requerimientos

  resources :areas

  resources :usuarios

  resources :aplicaciones

  resources :tipos_requerimientos

  root :to => 'planificaciones#index' 

end

app/models/semana.rb
# == Schema Information
#
# Table name: semanas
#
#  id         :integer         primary key
#  desde      :date
#  hasta      :date
#  created_at :timestamp
#  updated_at :timestamp
#

class Semana < ActiveRecord::Base

  # Crea todas las semanas del mes, de lunes a viernes
  def self.crear_semanas_mes(fecha)
    unless Semana.tiene_semanas_mes_creadas?(fecha)
      pibote = fecha.at_beginning_of_month
      
      until pibote.month == fecha.next_month.month do
        desde = pibote.next_monday
        hasta = desde.next_friday
        
        Semana.create(:desde => desde, :hasta => hasta) # Creo la semana

        pibote = hasta.next_monday
      end
    end
  end
  
  def self.tiene_semanas_mes_creadas?(fecha)
    principio_mes = fecha.at_beginning_of_month
    fin_mes = fecha.at_end_of_month
    
    Semana.exists?([" desde between :principio and :fin and hasta between :principio and :fin ", {:principio => principio_mes, :fin => fin_mes}])
  end

end

app/controllers/semanas_controller.rb
class SemanasController < ApplicationController
  # GET /semanas
  # GET /semanas.json
  def index
    @semanas = Semana.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @semanas }
    end
  end

  # GET /semanas/1
  # GET /semanas/1.json
  def show
    @semana = Semana.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @semana }
    end
  end

  # GET /semanas/new
  # GET /semanas/new.json
  def new
    @semana = Semana.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @semana }
    end
  end

  # GET /semanas/1/edit
  def edit
    @semana = Semana.find(params[:id])
  end

  # POST /semanas
  # POST /semanas.json
  def create
    @semana = Semana.new(params[:semana])

    respond_to do |format|
      if @semana.save
        format.html { redirect_to @semana, notice: 'Semana was successfully created.' }
        format.json { render json: @semana, status: :created, location: @semana }
      else
        format.html { render action: "new" }
        format.json { render json: @semana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /semanas/1
  # PUT /semanas/1.json
  def update
    @semana = Semana.find(params[:id])

    respond_to do |format|
      if @semana.update_attributes(params[:semana])
        format.html { redirect_to @semana, notice: 'Semana was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @semana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semanas/1
  # DELETE /semanas/1.json
  def destroy
    @semana = Semana.find(params[:id])
    @semana.destroy

    respond_to do |format|
      format.html { redirect_to semanas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/semanas_helper.rb
module SemanasHelper
end

app/views/semanas/_form.html.erb
<%= form_for(@semana) do |f| %>
  <% if @semana.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semana.errors.count, "error") %> prohibited this semana from being saved:</h2>

      <ul>
      <% @semana.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desde %><br />
    <%= f.date_select :desde %>
  </div>
  <div class="field">
    <%= f.label :hasta %><br />
    <%= f.date_select :hasta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semanas/edit.html.erb
<h1>Editing semana</h1>

<%= render 'form' %>

<%= link_to 'Show', @semana %> |
<%= link_to 'Back', semanas_path %>

app/views/semanas/index.html.erb
<h1>Listing semanas</h1>

<table>
  <tr>
    <th>Desde</th>
    <th>Hasta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @semanas.each do |semana| %>
  <tr>
    <td><%= semana.desde %></td>
    <td><%= semana.hasta %></td>
    <td><%= link_to 'Show', semana %></td>
    <td><%= link_to 'Edit', edit_semana_path(semana) %></td>
    <td><%= link_to 'Destroy', semana, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Semana', new_semana_path %>

app/views/semanas/new.html.erb
<h1>New semana</h1>

<%= render 'form' %>

<%= link_to 'Back', semanas_path %>

app/views/semanas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desde:</b>
  <%= @semana.desde %>
</p>

<p>
  <b>Hasta:</b>
  <%= @semana.hasta %>
</p>


<%= link_to 'Edit', edit_semana_path(@semana) %> |
<%= link_to 'Back', semanas_path %>